### ISSUE TITLE
Documentation Broken

### ISSUE THREAD

**Issue by c0d3machin3** [meraki/dashboard-api-ansible#3]
The old cisco.meraki.meraki* module documentation at https://docs.ansible.com/ansible/latest/collections/cisco/meraki/index.html all seems to be broken.

Ex. "Missing documentation or could not parse documentation: cisco.meraki.meraki_ms_l3_interface did not contain a DOCUMENTATION attribute"

**Comment by felixfontein** [comment]
That's not very surprising, since the YAML for these modules is totally broken:
https://github.com/meraki/dashboard-api-ansible/blob/main/plugins/modules/meraki_network_settings.py#L54-L72

This would have been flagged by the sanity tests, but for some reason they are all deactivated for these modules:
https://github.com/meraki/dashboard-api-ansible/blob/main/tests/sanity/ignore-2.16.txt#L1-L129.

**Comment by fmunozmiranda** [comment]
Hi @c0d3machin3 doc should be fixed in 2.16.2, thanks for reporting, please verify it and feel free to close the issue.

**Comment by fmunozmiranda** [comment]
@c0d3machin3 you should use this documentation:
https://meraki.github.io/dashboard-api-ansible/v2.16.2/plugins/index.html#plugin-index

While cisco.meraki is updated in `ansible-collections`

**Comment by felixfontein** [comment]
Please note that the sanity errors are still failing. Please remove all `ansible-doc!skip` and `validate-modules!skip` entries from the `tests/sanity/ignore-*.txt` files and check out what the sanity tests are saying. Everything that they return is a **error in the module** that must be fixed, not something that should be ignored.

**Comment by fmunozmiranda** [comment]
@felixfontein we are working on it, thanks

**Comment by fmunozmiranda** [comment]
Documentation fixed.
